[package]
name = "rd"
version = "0.1.0"
authors = ["Radek Kysely <radek@kysely.org>"]
edition = "2018"

[dependencies]
bytes = "0.4.11"
log = "0.4.6"
pretty_env_logger = "0.3.0"
rand = "0.6.5"
zmq = "0.8"
